## Import Numpy 

In [1]:
import numpy as np

## Basic Example 

In [2]:
import numpy as np
a=np.array([1,2,3])
print (a)

[1 2 3]


## Create a NumPy array:

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Create a 0-D array with value 42

In [5]:
import numpy as np

arr = np.array(42)

print(arr)

42


## Create a 1-D array containing the values 1,2,3,4,5:

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## Check Number of Dimensions

In [10]:
import numpy as np

a = np.array(42) #0D
b = np.array([1, 2, 3, 4, 5]) #1D
c = np.array([[1, 2, 3], [4, 5, 6]]) #2D
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3D

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Create an array with 5 dimensions and verify that it has 5 dimensions:

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Get the first element from the following array:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


## Get the second element from the following array.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


## Get third and fourth elements from the following array and add them.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


## Access the element on the first row, second column:

In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


## Access the third element of the second array of the first array

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


##  Print the last element from the 2nd dim:

In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


##  Print the last element from the 2nd dim:

In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


<h1 style="color:Tomato;" > Sliceing the  elements </h1>

## Slice elements from index 1 to index 5 from the following array:

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


## Slice elements from index 4 to the end of the array

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


## Slice elements from the beginning to index 4 (not included):

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


## Negative SlicingSlice elements from the beginning to index 4 (not included):

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]
