<h1>Import Numpy</h1>

In [3]:
import numpy as np

<h1>Basic Example</h1>

In [2]:
import numpy as np

list1 = [11,22,33]
a = np.array(list1)
print(a)

[11 22 33]


<h1>Create a numpy Array:</h1>

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<h1>Create a 0-D Array with value 42:</h1>

In [8]:
import numpy as np

arr = np.array(42)

print(arr)

42


<h1>Create a 2-D Array conatining two arrays with the values 1,2,3 and 4,5,6</h1>

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


<h1>Create a 3-D Array containing three arrays with the values:</h1>

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],  [[7, 8, 9], [10, 11, 12]]])
print(arr)
add = arr[0,0,2]+arr[1,1,1]+arr[2,1,0]
print(add)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]
24
